// Package tools ...
// Generated by github.com/jademperor/go-tools/convstruct
// This will only be generated while the target file is not existed
package tools

import (
	"github.com/jademperor/go-tools/pkg/testdata"

	gorm "github.com/jinzhu/gorm"

	time "time"

	testdata2 "github.com/jademperor/go-tools/convstruct/testdata2"
)

// CustomModel description here
type CustomModel struct {
	Model gorm.Model `json:"model,omitempty"`

	Name string `json:"name,omitempty"`

	Age int `json:"age,omitempty"`

	Birthday time.Time `json:"birthday,omitempty"`

	SubModel testdata2.SubModel `json:"sub_model,omitempty"`

	SubModelPtr *testdata2.SubModel `json:"sub_model_ptr,omitempty"`

	Int testdata.SelfInt `json:"int,omitempty"`

	M testdata.SelfModel `json:"m,omitempty"`
}

// LoadCustomModelFromModel func to load data from model
func LoadCustomModelFromModel(m *testdata.CustomModel) *CustomModel {
	return &CustomModel{

		Model: m.Model,

		Name: m.Name,

		Age: m.Age,

		Birthday: m.Birthday,

		SubModel: m.SubModel,

		SubModelPtr: m.SubModelPtr,

		Int: m.Int,

		M: m.M,
	}
}
