package main

// TmplHeader is a template of `convstruct`
const TmplHeader = `
// Package {{.PkgName}} ...
// Generated by github.com/jademperor/go-tools/convstruct
// This will only be generated while the target file is not existed
package {{.PkgName}}
`

// TmplImport is a template of `convstruct`
const TmplImport = `
import (
	{{range $idx, $import := .Imports}}
	{{$import.Name}} {{$import.Path}}
	{{end}}
)
`

// TmplMethod is a template of `convstruct`
const TmplMethod = `
// Load{{.Name}}FromModel func to load data from model
func Load{{.Name}}FromModel(m *{{.FromPkg.Name}}.{{.Name}}) *{{.Name}} {
	return &{{.Name}} {
		{{range $index, $field := .Fields}}
			{{$field.Name}}: m.{{$field.Name}},
		{{end}}
	}
}
`

// TmplStruct is a template of `convstruct`
const TmplStruct = `
// {{.Name}} description here
type {{.Name}} struct {
	{{range $index, $field := .Fields}}
		{{$field.Name}} {{$field.Expr}} {{$field.Tag}} 
	{{end}}
}
`
