// Package out ...
// Generated by github.com/jademperor/go-tools/convstruct
// This will only be generated while the target file is not existed
package out

import (
	time "time"

	test2 "github.com/jademperor/go-tools/examples/convstruct/pkg-test2"
	gorm "github.com/jinzhu/gorm"

	// TODO: generate this import spec
	test1 "github.com/jademperor/go-tools/examples/convstruct/pkg-test1"
)

// CustomModel description here
type CustomModel struct {
	Model       gorm.Model      `json:"model,omitempty"`
	Name        string          `json:"name,omitempty"`
	Age         int             `json:"age,omitempty"`
	Birthday    time.Time       `json:"birthday,omitempty"`
	SubModel    test2.SubModel  `json:"sub_model,omitempty"`
	SubModelPtr *test2.SubModel `json:"sub_model_ptr,omitempty"`
	Int         test1.SelfInt   `json:"int,omitempty"`
	M           test1.SelfModel `json:"m,omitempty"`
}

// LoadCustomModelFromModel func to load data from model
func LoadCustomModelFromModel(m *test1.CustomModel) *CustomModel {
	return &CustomModel{
		Model:       m.Model,
		Name:        m.Name,
		Age:         m.Age,
		Birthday:    m.Birthday,
		SubModel:    m.SubModel,
		SubModelPtr: m.SubModelPtr,
		Int:         m.Int,
		M:           m.M,
	}
}
